export { default as VideosView } from './_Videos.svelte'
export { default as TopInfoView } from './_TopInfo.svelte'
export { default as DocumentsView } from './_Documents.svelte'
export { default as HowToHelpView } from './_HowToHelp.svelte'
export { default as AnimalCardView } from './_AnimalCard.svelte'
export { default as DescriptionView } from './_Description.svelte'