export { default as VideosEdit } from './_Videos.svelte'
export { default as TopInfoEdit } from './_TopInfo.svelte'
export { default as DocumentsEdit } from './_Documents.svelte'
export { default as HowToHelpEdit } from './_HowToHelp.svelte'
export { default as DescriptionEdit } from './_Description.svelte'